def main():
    print("Brew the cat wake up.")
    print("He stretch orange paws.")
    print("Sun shine on his fur.")
    print("Time for adventure.")
    print("Brew run out the back door.")
    print("He run fast into the big green forest.")
    print("Trees tall. Leaves crunch.")
    print("Brew smell something funny.")
    print("He look under a log.")
    print("A green snake hiss.")
    print("Sssssss.")
    print("Brew not scared.")
    print("Brew lift paw.")
    print("Smack.")
    print("He bop the snake on the nose.")
    print("Snake slither away fast.")
    print("Brew purr. Good game.")
    print("Brew frolic in the tall grass.")
    print("He jump over branches.")
    print("He see another snake.")
    print("This one brown and long.")
    print("Brew sneak up quiet.")
    print("Smack.")
    print("Another bop.")
    print("Brown snake go hide.")
    print("Sun go down. Sky get dark.")
    print("Stars come out.")
    print("Brew still frolic. Night time fun.")
    print("He see a shiny snake in moonlight.")
    print("Smack. Smack. Double bop.")
    print("Shiny snake leave him alone.")
    print("Brew tired now.")
    print("Paws hurt from too much smacking.")
    print("Tummy rumble. Want tuna.")
    print("Brew turn around. Walk out of forest.")
    print("He walk up path to house.")
    print("Light on in window.")
    print("Owner stand on porch. Look sad.")
    print("Owner call, 'Brew! Where are you?'")
    print("Brew say, 'Meow.'")
    print("Owner run and pick Brew up.")
    print("Owner hug him tight. Very worried.")
    print("Brew purr loud.")
    print("He safe home. Eat big bowl of fish.")
    print("No more snakes tonight.")

if __name__ == "__main__":
    main()