extends Node

func _ready():
    print("Brew walk in tall green grass.")
    print("See small red circle on leaf.")
    print("Circle have six black dots. Shiny shell.")
    print("Ladybug.")
    print("Brew creep close. Belly drag on dirt.")
    print("Tail twitch. One, two, pounce!")
    print("Ladybug open hard shell. Clear wings come out.")
    print("Buzz. Ladybug fly to sky.")
    print("Brew miss. Paw hit empty leaf.")
    print("Brew walk more. Hear noise.")
    print("Click, click. See big green bug.")
    print("Bug have very long back legs. Spiky knees.")
    print("Grasshopper chew on thick weed.")
    print("Brew sneak behind grey rock.")
    print("Wiggle butt. Get ready.")
    print("Brew jump high!")
    print("Grasshopper see Brew. Grasshopper jump higher.")
    print("Boing. Grasshopper land ten feet away.")
    print("Brew run fast. Chase over sticks and mud.")
    print("Grasshopper boing again. Gone in thick bush.")
    print("Brew stop. Pant hard.")
    print("Look up. See big blue flash.")
    print("Wings big as hands. Flap very soft.")
    print("Butterfly.")
    print("Wings blue like sky, black lines like glass window.")
    print("Butterfly fly zig zag. Left, right, up, down.")
    print("Brew run in circles. Try follow blue flashes.")
    print("Brew stand on back legs. Reach paws up high.")
    print("Swipe left! Swipe right!")
    print("Butterfly dance in wind. Too high for Brew.")
    print("Butterfly float over wooden fence. Gone.")
    print("Brew dizzy now. Very hot.")
    print("Look down at dirt path.")
    print("See black rock moving slow.")
    print("Big ground beetle. Shell black like coal. Look heavy.")
    print("Beetle walk clunk-clunk. Six slow legs.")
    print("Brew walk over. Sniff black shell.")
    print("Beetle stop. Pull legs inside. Become rock.")
    print("Brew poke beetle with one sharp claw.")
    print("Beetle stay still. Very boring bug.")
    print("Brew give up.")
    print("Legs feel heavy. Paws hurt.")
    print("Find soft green moss under big oak tree.")
    print("Brew lay down. Curl into tight orange ball.")
    print("Wrap fluffy tail over cold nose.")
    print("Big yawn. Show sharp teeth.")
    print("Close eyes. Purr start loud like small engine.")
    print("Brew sleep deep. Dream of slow, tasty bugs.")